### ISSUE TITLE
Machine.State always renders child functions

### ISSUE THREAD

**Issue by ShMcK** [avaragado/xstateful-react#4]
Child functions appear to not listen to the is/not condition.

```jsx
<Machine.State  is="SomeState">
  {(props) => (
     <div>Always renders regardless of condition</div>
  )}
</Machine.State>

<Machine.State  is="SomeState" render={(props) => (
  <div>conditionally renders as expected</div>
)} />
```

**Comment by avaragado** [comment]
This is by design, to closely match the behaviour of react-router (see https://reacttraining.com/react-router/web/api/Route). With children functions, there's an extra prop `match` with the result of the condition.

See https://github.com/avaragado/xstateful-react#machine for the rules followed for the `component`, `render` and `children` props.
